### ISSUE TITLE
Reset to previous values

### ISSUE THREAD

**Issue by darkain** [thindil/gameboost#1]
https://github.com/thindil/gameboost/blob/158697aacdbbd680bb4112c337892224e5c242fd/gameboost.sh#L117

For this, I think it would be better at the beginning of the script to record the existing value, and return the system to that earlier value, instead of arbitrarily setting it to a static value.

**Comment by thindil** [comment]
Hello,

Yes, definitely could be. 😉 At this moment, the script is very simple, and many things here can be upgraded. I will try to do it “soon”, unless someone wants to do it.

**Comment by thindil** [comment]
Ok, I think it should now be implemented. I also added it for Nvidia `PowerMizer` setting.

Thank you for your proposition. I close the issue, but if you think, there is something more to do or discuss, feel free to reopen it or create a new one.

Take care.
